### ISSUE TITLE
Add support for storage size to Enum

### ISSUE THREAD

**Issue by dmbates** [dmbates/FlatBuffers.jl#1]
In Julia an `Enum` value is an `Int32`.  In the FlatBuffers IDL the storage size of an `enum` is user-specified.  Because of the alignment of scalars in the inlined part of the binary representation these values can be read as Int32` and converted to the Enum type.  However, I think this may fail on an array.

Probably should create a FlatBuffers.fbenum type that contains the Enum and the storage type and use that.

**Comment by quinnj** [comment]
This is now supported in #7 by doing
```julia
FlatBuffers.enumtype(T) = UInt8
```
I'm planning to add a convenience macro `@enumtype T UInt8`, similar to the other "modifier" macros.
