### ISSUE TITLE
Add Base.read method for user-declared isbits types (i.e. a struct in the IDL)

### ISSUE THREAD

**Issue by dmbates** [dmbates/FlatBuffers.jl#2]
For example the `Vec3` type in `test/monster.fbs` has a length of 12 bytes.  A scalar will be stored inline, I just haven't worked out how to take a vector of 12 bytes and create an instance of the type from it.  It would not be too difficult to loop over `Vec3.types` to get the types, read them from the IO object and create the Julia `immutable Vec3` from them but that seems indirect.  There has to be a cleaner method than that.

**Comment by quinnj** [comment]
Fixed by #7. The new approach actually deserializes the entire root table all at once like:
```julia
fb = FlatBuffers.Table(RootTable, buf, root_pos)
rootable = FlatBuffers.read(fb)
```
This means that all nested struct types are handled automatically while deserializing the parent table.
