### ISSUE TITLE
Don't convert a union in the IDL to a Julia Union type

### ISSUE THREAD

**Issue by dmbates** [dmbates/FlatBuffers.jl#3]
The Julia `Union` datatype will probably not work for types declared as `union` in the IDL.  The IDL `union` requires that the types be a vector because they are stored inliine as an index into the vector  of types followed by the offset to the value.  I don't think the ordering is preserved in the Julia `Union`.  For example, in the `Feather` package the definition of `TypeMetadata` is

```jl
typealias TypeMetadata Union{CategoryMetadata, TimestampMetadata, DateMetadata, TimeMetadata}
```

but it prints as

```jl
julia> Feather.TypeMetadata
Union{Feather.CategoryMetadata,Feather.DateMetadata,Feather.TimeMetadata,Feather.TimestampMetadata}
```

It might be easier to impose the ordering in the .types `svec` if I can figure out how to do so.

```jl
julia> Feather.TypeMetadata.types
svec(Feather.DateMetadata,Feather.TimeMetadata,Feather.TimestampMetadata,Feather.CategoryMetadata)
```
Of course, there may be a reason for the observed ordering.

It may be easiest just to convert a `union` in the IDL to a `Vector{DataType}` instead of a `Union` in Julia.

**Comment by quinnj** [comment]
This is now supported in #7 by utilizing the `@union` convenience macro, so usage is:
```julia
@union TypeMetadata Union{CategoryMetadata, TimestampMetadata, DateMetadata, TimeMetadata}
```
You can then create other tables that include the union like
```julia
type RootTable
    x_type::Int8
    x::TypeMetadata
end

RootTable(x) = RootTable(FlatBuffers.typeorder(TypeMetadata, typeof(x)), x)
```
Note that we need to include the extra `x_type` field in the `RootTable` type to hold the union type; we also provide an additional constructor that takes the input `x` and figures out the `TypeMetadata` by calling `FlatBuffers.typeorder(TypeMetadata, typeof(x))`. I think in the future we can provide additional convenience macros, so usage would be:
```julia
@table type RootTable
    x::TypeMetadata
end
```
which will detect that a union field is needed and can provide the additional constructor automatically.
