### ISSUE TITLE
FlatBuffers2.jl

### ISSUE THREAD

**Issue by quinnj** [dmbates/FlatBuffers.jl#6]
Hey @dmbates, so I've had a bit of free time on my hands the last couples weeks and I've taken on the task of getting feather fully functional for Julia. As I dug into things, I realized that we needed to take FlatBuffers.jl a step further to allow writing a buffer in addition to reading. I ended up just creating a separate repo while I did all the dev work, starting from what you had already done on the reading side plus the [Go](https://github.com/google/flatbuffers/tree/master/go) implementation and working from there. Everything's in pretty good shape now for FlatBuffers2 with a pretty robust test suite and some good examples (feather metadata being my primary concern). I'm just finishing getting the appveyor setup for windows testing and finishing the docs/README.

I guess I'm really opening this issue to figure out how to move forward. Should I do a big "overhaul" PR to this repo? Delete this and rename [FlatBuffers2.jl](https://github.com/quinnj/FlatBuffers2.jl)? Move this repo to an org? (JuliaStats or JuliaDB? Maybe JuliaIO?) Or you could just add me as a main collaborator/owner for this repo and we can work from here? I really don't have strong preferences, as long as I can have the write access to fix bugs as they come up. Thoughts?

**Comment by dmbates** [comment]
Sorry not to respond to this email quickly.  For some reason gmail decided to redirect all my mail from `notifications@github.com` to the Spam folder.  I should have noticed that things were a bit quieter.

I would be delighted to collaborate on `FlatBuffers.jl` and `Feather.jl`.  As for a mechanism I don't have strong preferences either.  I have added you as a collaborator in `FlatBuffers.jl` and would be happy to have you create a pull request from your repository.

This comes at a very good time for me.  I have a fairly good method of reading feather files in the `dmb/Cxx` branch of `Feather.jl` but writing files by going through C++ was just getting too tedious.  I will be glad to have you incorporate your changes for writing Flatbuffers.  Once that is in I think it will be straightforward to write feather files.

**Comment by quinnj** [comment]
Sounds great. I made the PR with the big overhaul/native implementation.

Mind adding me as a collaborator to Feather.jl as well? I actually have a native implementation for reading/writing feather files as well. It needs a little more cleanup/ironing out, but I was able to round trip all the feather files you currently have in the test/data directory (i.e. read them all into Julia, then write my Julia structure back out to a valid feather file). I'll clean that up over the next few days and do another PR for Feather.jl

**Comment by dmbates** [comment]
@quinnj I have added you as a collaborator n `Feather.jl`.

We should consider moving this repository to one of the groups you mentioned (`JuliaDB` or `JuliaIO` - I think `JuliaStats` is a reasonable choice for `Feather` but probably not for `FlatBuffers`).  As you have done all the work on this version I really shouldn't be taking the credit.

I believe you will be at JuliaCon in a couple of weeks.  Perhaps we can have an informal meeting, inviting others who may be interested in FlatBuffers and Feather.
